site_name: My Blog
site_description: Thinking & Writing
site_author: andyhoang
site_url: 'https://andyhoang.github.io/'
repo_name: null
repo_url: "https://github.com/AndyHoang/AndyHoang.github.io"
theme:
  name: material

markdown_extensions:
  - meta
extra:
  disqus: andyhoang-me
nav:
  - Home: index.md
  - Tech:
    - 'Setup my first blog': tech/2017-03-19-60-minutes-setting-up-my-first-blog.md
  - Poet:
    - 'poet/hoa-roi-nuoc-chay.md'
    
