name: ci
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install \
          mkdocs-material \
          mkdocs-awesome-pages-plugin \
          mkdocs-encryptcontent-plugin==2.4.5 \
          mkdocs-git-revision-date-localized-plugin==1.1.0 \
          mkdocs-material==9.0.15 \
          mkdocs-material-extensions==1.1.1

      - run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_PACKAGES: build-base
          CUSTOM_DOMAIN: andyhoang.me
#jobs:
  #deploy:
    #name: Deploy docs
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout main
        #uses: actions/checkout@v2

      #- name: Deploy docs
        #uses: mhausenblas/mkdocs-deploy-gh-pages@master
        ## Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #EXTRA_PACKAGES: build-base
          #CUSTOM_DOMAIN: andyhoang.me
